id: I40731973
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 16:01:42.506568
last_modified: 2023-02-08 16:01:42.506760
source_metadata:
  title: 'Vasubandhu: Abhidharmakośabhāṣya'
  language: sa
bases:
  '6199':
    base_file: 6199.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
